AT_PACKAGE_NAME      = "Luke"
AT_PACKAGE_TARNAME   = "luke"
AT_PACKAGE_VERSION   = "0"
AT_PACKAGE_STRING    = "Luke 0"
AT_PACKAGE_BUGREPORT = "http://github.com/gvvaughan/luke/issues"
AT_PACKAGE_URL       = "http://github.com/gvvaughan/luke/"
